<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\FacultyModule\" />
    <Folder Include="Entities\AnnouncementAndDownload\" />
    <Folder Include="Entities\FYPPropsalModule\" />
    <Folder Include="Entities\StudentModule\" />
    <Folder Include="Entities\UserManagmentModule\" />
    <Folder Include="Enums\" />
    <Folder Include="RepoInterfaces\" />
  </ItemGroup>
</Project>
